setup for sqllite3
adelowo/sdump pull request #37
Opened 2024-10-03 06:36 UTC by oneEyedSunday

For https://github.com/adelowo/sdump/issues/33

2024-10-13 15:53 UTC, adelowo requested changes
Looks good to me asides the suggested Changes

2024-10-13 15:53 UTC, adelowo commented on config/config.go
> +	if cfg.HTTP.Database.Driver == "sqllite" {
`sqlite` instead

2024-10-13 15:53 UTC, adelowo commented on datastore/sqlite/sqlite.go
> +		db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose(true)))
Please let us add https://github.com/oiime/logrusbun instead so the log format stays consistent. Always wanted to do this but never had the time

2024-10-13 15:55 UTC, adelowo commented on config/config.go
> +		Driver     string `mapstructure:"driver" json:"driver,omitempty" yaml:"driver,omitempty"`
Please define enums for this. So people can know the supported driver types

2024-10-13 22:28 UTC, adelowo commented on config/config.go
> +}
also can we encapsulate this into just one `New` function and depending on the driver, we return the correctly configured one. having Postgres and sqlite packages just to export `New` seems overkill to me

2024-10-15 13:12 UTC, adelowo commented
aside these, I think I am happy to merge this.

2024-10-15 13:13 UTC, oneEyedSunday commented
> aside these, I think I am happy to merge this.

Hey man. I'll get to this in the next 24

2024-10-15 17:05 UTC, oneEyedSunday commented
> aside these, I think I am happy to merge this.

requested changes added.

2024-10-16 10:02 UTC, adelowo commented
> > aside these, I think I am happy to merge this.
> 
> requested changes added.

thanks a lot for the work! Greatly appreciated!

2024-10-16 10:02 UTC, adelowo approved these changes

2024-10-16 10:03 UTC, merged